from _typeshed import Incomplete
from collections.abc import Iterable
from meteoforge.spatial_temporal.validators import validate_mf_location as validate_mf_location
from pyproj import CRS
from shapely.geometry import Polygon
from typing import Any

class MFLocation:
    crs: Incomplete
    x: Incomplete
    y: Incomplete
    point: Incomplete
    def __init__(self, x: float, y: float, crs: int | str | CRS = 4326) -> None: ...
    def to(self, target_crs: int | str | CRS) -> MFLocation: ...
    def equals(self, other: MFLocation, tol: float = 1e-06, crs: int | str | CRS = 4326) -> bool: ...
    def __eq__(self, other: Any) -> bool: ...

class MFLocationList:
    crs: Incomplete
    locations: list[MFLocation]
    def __init__(self, locations: Iterable[MFLocation] | None = None, crs: int | str | CRS = 4326) -> None: ...
    def append(self, location: Any) -> None: ...
    def __getitem__(self, idx: int) -> MFLocation: ...
    def __setitem__(self, idx: int, value: MFLocation) -> None: ...
    def __delitem__(self, idx: int) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, item: MFLocation) -> bool: ...
    def find_nearby(self, item: MFLocation, tol: float = 1e-06) -> MFLocation | None: ...

class MFLocationVector:
    crs: Incomplete
    locations: list[MFLocation]
    polygon: Polygon | None
    def __init__(self, locations: Iterable[MFLocation] | None = None, crs: int | str | CRS = 4326) -> None: ...
    def append(self, location: Any) -> None: ...
    def contains(self, location: MFLocation, tol: float = 1e-06) -> bool: ...
    def __contains__(self, item: MFLocation) -> bool: ...
    def __getitem__(self, idx: int) -> MFLocation: ...
    def __setitem__(self, idx: int, value: MFLocation) -> None: ...
    def __delitem__(self, idx: int) -> None: ...
    def __len__(self) -> int: ...

def fuzzy_in(item: MFLocation, container: Iterable[MFLocation], tol: float = 1e-06, crs: int | str | CRS = 4326) -> bool: ...
