from meteoforge.logging.logging import logger as logger
from pyproj import CRS
from typing import Any

class CRSValidationError(ValueError): ...

def validate_mf_location(x: int | float, y: int | float, crs: CRS) -> bool: ...
def validate_mf_period(start_time: object, end_time: object) -> bool: ...
def validate_crs(crs: Any) -> bool: ...
def validate_location(x: int | float, y: int | float, crs: CRS) -> bool: ...
