# SPDX-FileCopyrightText: 2025-2026 Contributors to the MeteoForge project
# SPDX-License-Identifier: MPL-2.0

from typing import Any

from pyproj import CRS

from meteoforge.logging.logging import logger as logger

class CRSValidationError(ValueError): ...

def validate_mf_location(x: int | float, y: int | float, crs: CRS) -> bool: ...
def validate_mf_period(start_time: object, end_time: object) -> bool: ...
def validate_crs(crs: Any) -> bool: ...
def validate_location(x: int | float, y: int | float, crs: CRS) -> bool: ...
