# SPDX-FileCopyrightText: 2025-2026 Contributors to the MeteoForge project
# SPDX-License-Identifier: MPL-2.0

# This pre-commit config can be installed by running 'pre-commit install --install-hooks'.
# All configs are set in pyproject.toml.

# Hooks
repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [ "--fix" ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: [ "types-shapely", "pydantic" ]
        exclude: ^typings/

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        exclude: >
          (?x)^(
              LICENSES/.*
              | .*\.svg
              | .*\.lock
          )$

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.3
    hooks:
      - id: uv-lock

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
        args: [ "--config", ".markdownlint.yaml" ]
