# SPDX-FileCopyrightText: 2025-2026 Contributors to the MeteoForge project
# SPDX-License-Identifier: MPL-2.0

[project]
name = "meteoforge"
version = "3.0.0-alpha.1"
description = "The MeteoForge Project provides a set of tools to work with meteorological data, focused on downloading, processing and formatting datasets from various sources."
authors = [
    { name = "Raoul Linnenbank", email = "58594297+rflinnenbank@users.noreply.github.com" }
]
license = { text = "MPL2.0" }
readme = "README.md"
requires-python = ">=3.13,<3.14"  # 3.14 not supported yet by all dependencies (Atheris, PyProj)
dynamic = ["dependencies"]

[tool.poetry.urls]
homepage = "https://github.com/alliander-opensource/meteoforge"
repository = "https://github.com/alliander-opensource/meteoforge"
documentation = "https://github.com/alliander-opensource/meteoforge"

[tool.poetry.dependencies]
pyproj = "^3.7.2"
colorlog = "^6.10.1"
pydantic = "^2.13.3"
xarray = "^2026.4.0"
zarr = "^3.1.6"
numpy = "^2.4.4"
netcdf4 = "^1.7.4"
dask = "^2026.3.0"
shapely = "^2.1.2"

[tool.poetry.group.dev.dependencies]
coverage = "^7.13.5"
pytest = "^9.0.3"
pre-commit = "^4.6.0"
ruff = "^0.15.12"
mypy = "^1.20.2"
fawltydeps = "^0.20.0"
types-pyyaml = "^6.0.12"
pytest-cov = "^7.1.0"
reuse = "^6.2.0"
types-shapely = "^2.1.0"
atheris = "^3.0.0"


[tool.poetry.group.docs.dependencies]
zensical = "^0.0.37"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
output-format = "github"
line-length = 120
show-fixes = true
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "migrations",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "UP",
    "B",
    "SIM",
    "I",
    "D",
]
ignore = [
    "D100",
    "D104",
    "D203",
    "D213",
]

[tool.ruff.lint.per-file-ignores]
"conftest.py" = ["E501"]

[tool.mypy]
packages = ["src.meteoforge"]
plugins = []
python_version = "3.13"
strict = true
exclude = ["tests/*", ".venv/*"]
disable_error_code = []
follow_imports = "normal"
ignore_missing_imports = false
show_error_codes = true
namespace_packages = true
explicit_package_bases = true
check_untyped_defs = true
allow_redefinition = true
no_implicit_optional = true
install_types = true
non_interactive = true
enable_error_code = []
files = ["src/meteoforge/spatial_temporal/locations.py"]

[tool.pylint.format]
max-line-length = 120

[tool.pytest.ini_options]
addopts = [
    "--cov",
    "--cov-branch",
    "--cov-report=xml",
    "--cov-report=term-missing"
]
minversion = "8.4.1"
testpaths = ["tests"]

[tool.coverage.run]
relative_files = false
omit = [
    "tests/*",
    ".venv/*",
]
