# SPDX-FileCopyrightText: 2025-2026 Contributors to the MeteoForge project
# SPDX-License-Identifier: MPL-2.0
# Required metadata
sonar.projectName=MeteoForge (Core System)
sonar.projectKey=alliander-opensource_meteoforge
sonar.organization=alliander-opensource
sonar.sourceEncoding=UTF-8
# Project folders
sonar.sources=src/meteoforge,src/meteoforge_tools
sonar.tests=tests
# Language
sonar.language=py
# Python versions
sonar.python.version=3.13
# Links
sonar.links.homepage=https://github.com/alliander-opensource/meteoforge/
sonar.links.ci=https://github.com/alliander-opensource/meteoforge/img/gitflow.svg
sonar.links.scm=https://github.com/alliander-opensource/meteoforge/
sonar.links.issue=https://github.com/alliander-opensource/meteoforge/issues
# Coverage
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/tests/**,**/*.svg
