# SPDX-FileCopyrightText: 2025-2026 Contributors to the MeteoForge project
# SPDX-License-Identifier: MPL-2.0
name: SonarCloud Scan
description: Runs SonarCloud scan with coverage artifact

inputs:
  GITHUB_TOKEN:
    required: true
    description: GitHub token
  SONAR_TOKEN:
    required: true
    description: SonarCloud token

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        fetch-depth: 0

    - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: coverage.xml
        path: ./

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8 # v5.0.0
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}
