name: Trivy Docker Image Scan
description: Scans a Docker image for vulnerabilities using Trivy

inputs:
  image:
    required: true
    description: Docker image to scan

runs:
  using: "composite"
  steps:
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b $HOME/bin
        echo "$HOME/bin" >> $GITHUB_PATH
      shell: bash

    - name: Scan Docker image with Trivy
      run: trivy image ${{ inputs.image }}
      shell: bash
