version: 1
disable_existing_loggers: false
formatters:
  color:
    class: colorlog.ColoredFormatter
    format: "%(asctime)s - %(name)s - %(log_color)s%(levelname)s%(reset)s - %(message)s"
    log_colors:
      DEBUG: green
      INFO: cyan
      WARNING: yellow
      ERROR: red
      CRITICAL: bold_red
  monocolor:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: color
    stream: ext://sys.stdout
loggers:
  meteoforge:
    level: DEBUG
    handlers: [ console ]
    propagate: no
root:
  level: WARNING
  handlers: [ console ]
